/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    DropdownItems: typeof import('./src/components/DropdownItems.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    NavItems: typeof import('./src/components/NavItems.vue')['default']
  }
}
